#Dockerfile for Taurob Gripper 
FROM ros:noetic
LABEL maintainer="michael.schebek@technikum-wien.at"
LABEL version="0.1"
LABEL description="ROS Test Container connected to Taurob Gripper via ArduinoMega"

#Update and upgrade, install ROS Serial for communication with Arduino
RUN apt update -y
RUN apt upgrade -y 
