#ROS Master for Taurob Gripper
FROM ros:noetic
LABEL maintainer="michael.schebek@technikum-wien.at"
LABEL version="0.1"
LABEL description="ROSMaster for Taurob Gripper Testing"

RUN apt update -y
RUN apt upgrade -y
